First attempt at part 2
thomaschester/PFMCPP_Project3 pull request #2
Opened 2022-03-13 01:47 UTC by thomaschester

2022-03-13 01:58 UTC, matkatmusic requested changes

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +    }
If you find yourself writing code like this:
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    else 
    {
        return anotherValue;
    }
}
```
You do not need the `else` block.  Here's why:
`return` statements are the last thing that **ever happens** in a function.
When the `if()` expression is evaluated as `true` and the block is entered, the `return aValue;` is the last line of code to be executed before the function exits.
but when the `if()` expression evaluates as `false` and the block is **NOT** entered, the next thing that happens is `return anotherValue;`
you have no code after the `else` block that needs executing, since your `else` block contains a `return` statement.
that means you do **NOT** need the `else` block, and it is just causing visual clutter.
```
int Type::someFunction()
{
    if( someExpression )
    {
        someStatement();
        return aValue;
    } 
    
    return anotherValue;
}
```
- [ ] revise

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +    }
- [ ] revise, see above comments

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise, see previous comments about the final `else { return whatever }`

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +}
each of these can be rewritten as:
```
variable = enabled;
```
However, this has the side effect of setting `variable` to whatever `enabled` is set to.
Right now you are only setting `variable` to `true` when `enabled` is `true`.
you should decide what these variables should be set to when `enabled` is `false`.

- [ ] Consider revising

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +        }
add curly braces around any blocks of code that are more than 1 line long.
this `if/else` stuff is more than 1 line long, so it should be surrounded by `{ }`
- [ ] revise

2022-03-13 01:58 UTC, matkatmusic commented on main.cpp
> +}
How do you exit this loop?
Loops have not been covered yet, and what you have written will never exit as long as `enabled` is true
- [ ] revise, either remove the loop or figure out a way to exit it.

2022-03-14 05:04 UTC, thomaschester commented on main.cpp
> +        }
I didn't notice I missed this, thanks. Why didn't the compiler flag that as an error or warning?

2022-03-14 06:36 UTC, matkatmusic approved these changes

2022-03-14 06:36 UTC, merged